[tools]
node = "22"
bun = "1"

[tasks.test]
run = [
    { task = "test:client" },
    { task = "test:server" },
    { task = "test:typecheck" },
]

[tasks."test:client"]
run = [
    "MEMORY_FS=0 npx vitest --config .config/vitest.client.ts --run tests/",
    # "MEMORY_FS=1 npx vitest --config .config/vitest.client.ts --run tests/omnio.test.ts",
]

[tasks."test:server"]
run = [
    "MEMORY_FS=0 npx vitest --config .config/vitest.server.ts --run tests/",
    "MEMORY_FS=1 npx vitest --config .config/vitest.server.ts --run tests/omnio.test.ts",
]

[tasks."test:typecheck"]
run = "npx tsc --noEmit"

[tasks.update]
run = [
    "mise upgrade",
    "npx npm-check-updates --target minor -u -x '@duckdb/duckdb-wasm' -x '@duckdb/node-api'",
    "bun install",
    "npx dprint config update",
    "npx playwright install chromium --with-deps",
    "bun audit",
]

[tasks.build]
run = "npx tsc -p .config/tsconfig.build.json"
