name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "チェックアウト"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: "mise をセットアップ"
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566  # v3.2.0

      - name: "依存関係をインストール"
        run: |
          bun i
          npx playwright install --with-deps

      - name: "テスト"
        run: mise run test

      - name: "ビルド"
        run: mise run build
